spring.application.name=paymentservice

spring.datasource.url=jdbc:postgresql://localhost:5432/grabit
spring.datasource.username=db_user_123
spring.datasource.password=db_password_@_1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=6060